name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm
    - uses: mansona/npm-lockfile-version@v1
    - run: npm i -g npm@8
    - run: npm ci
    - run: npm run lint
    - run: npm test
